"""Add elevation field to Tank model

Revision ID: 46ab8aa9f43c
Revises: b6afda779df5
Create Date: 2025-03-29 08:26:04.481325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ab8aa9f43c'
down_revision = 'b6afda779df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elevation', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.drop_column('elevation')

    # ### end Alembic commands ###
