"""Add indexes and soft delete functionality

Revision ID: 4f6adc5392e7
Revises: 46ab8aa9f43c
Create Date: 2025-03-31 22:19:55.748167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6adc5392e7'
down_revision = '46ab8aa9f43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarm', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alarm_acknowledged'), ['acknowledged'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarm_tank_id'), ['tank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarm_type'), ['type'], unique=False)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_tank_id'), ['tank_id'], unique=False)

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_tank_id'))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('alarm', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alarm_type'))
        batch_op.drop_index(batch_op.f('ix_alarm_tank_id'))
        batch_op.drop_index(batch_op.f('ix_alarm_acknowledged'))

    # ### end Alembic commands ###
