import sys
import os
import sqlite3
import psycopg2
import datetime
import time
import logging
import csv
import tempfile

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler("sqlite_to_timescaledb_migration.log"),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger("sqlite_to_timescaledb_migration")

# SQLite database path
SQLITE_DB_PATH = 'instance/fuel_tank.db'  # Update this to your SQLite DB path

# PostgreSQL connection parameters
PG_PARAMS = {
    'dbname': 'fuel_tank_monitoring',
    'user': 'fuel_tank_user',
    'password': os.environ.get('PG_PASSWORD'),
    'host': 'localhost',
    'port': '5432'
}

def get_sqlite_tables():
    """Get list of tables from SQLite database"""
    conn = sqlite3.connect(SQLITE_DB_PATH)
    cursor = conn.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = [row[0] for row in cursor.fetchall()]
    conn.close()
    return tables

def get_sqlite_table_schema(table_name):
    """Get schema for a specific table from SQLite database"""
    conn = sqlite3.connect(SQLITE_DB_PATH)
    cursor = conn.cursor()
    cursor.execute(f"PRAGMA table_info({table_name});")
    columns = cursor.fetchall()
    conn.close()
    return columns

def sqlite_to_postgres_type(sqlite_type):
    """Convert SQLite type to PostgreSQL type"""
    sqlite_type = sqlite_type.upper()
    if 'INT' in sqlite_type:
        return 'INTEGER'
    elif 'CHAR' in sqlite_type or 'TEXT' in sqlite_type or 'CLOB' in sqlite_type:
        return 'TEXT'
    elif 'REAL' in sqlite_type or 'FLOA' in sqlite_type or 'DOUB' in sqlite_type:
        return 'FLOAT'
    elif 'BOOL' in sqlite_type:
        return 'BOOLEAN'
    elif 'DATE' in sqlite_type or 'TIME' in sqlite_type:
        return 'TIMESTAMP'
    else:
        return 'TEXT'  # Default to TEXT for unknown types

def create_postgres_tables():
    """Create tables in PostgreSQL based on SQLite schema"""
    tables = get_sqlite_tables()
    
    # Connect to PostgreSQL
    conn = psycopg2.connect(**PG_PARAMS)
    cursor = conn.cursor()
    
    # PostgreSQL reserved keywords that need quoting
    reserved_keywords = ['user', 'group', 'order', 'table', 'select', 'where', 'from', 'limit', 'offset', 'having']
    
    for table_name in tables:
        if table_name == 'sqlite_sequence':
            continue  # Skip SQLite internal tables
            
        # Check if table name is a reserved keyword and quote it if necessary
        pg_table_name = f'"{table_name}"' if table_name.lower() in reserved_keywords else table_name
        
        logger.info(f"Creating table {table_name} in PostgreSQL...")
        
        # Get table schema from SQLite
        columns = get_sqlite_table_schema(table_name)
        
        # Create table in PostgreSQL
        create_table_sql = f"CREATE TABLE IF NOT EXISTS {pg_table_name} (\n"
        
        column_defs = []
        primary_keys = []
        
        for col in columns:
            col_id, col_name, col_type, not_null, default_val, is_pk = col
            
            # Check if column name is a reserved keyword and quote it if necessary
            pg_col_name = f'"{col_name}"' if col_name.lower() in reserved_keywords else col_name
            
            # Special handling for boolean columns in SQLite
            if table_name == 'user' and col_name == 'is_active':
                pg_type = 'BOOLEAN'
            else:
                # Convert SQLite type to PostgreSQL type
                pg_type = sqlite_to_postgres_type(col_type)
            
            # Build column definition
            col_def = f"{pg_col_name} {pg_type}"
            
            if is_pk:
                primary_keys.append(pg_col_name)
                if pg_type == 'INTEGER':
                    col_def += " GENERATED BY DEFAULT AS IDENTITY"
            
            if not_null:
                col_def += " NOT NULL"
                
            if default_val is not None:
                if default_val == 'CURRENT_TIMESTAMP':
                    col_def += " DEFAULT CURRENT_TIMESTAMP"
                elif pg_type == 'TEXT':
                    col_def += f" DEFAULT '{default_val}'"
                else:
                    col_def += f" DEFAULT {default_val}"
                    
            column_defs.append(col_def)
        
        # Add primary key constraint if any
        if primary_keys:
            column_defs.append(f"PRIMARY KEY ({', '.join(primary_keys)})")
            
        create_table_sql += ',\n'.join(column_defs)
        create_table_sql += "\n);"
        
        # Create the table
        cursor.execute(create_table_sql)
        
        logger.info(f"Table {table_name} created successfully.")
    
    # Commit changes
    conn.commit()
    cursor.close()
    conn.close()
    
    logger.info("All tables created in PostgreSQL.")

def migrate_table_data(table_name):
    """Migrate data from SQLite table to PostgreSQL"""
    # Connect to SQLite
    sqlite_conn = sqlite3.connect(SQLITE_DB_PATH)
    sqlite_cursor = sqlite_conn.cursor()
    
    # Get column names and types
    sqlite_cursor.execute(f"PRAGMA table_info({table_name});")
    columns_info = sqlite_cursor.fetchall()
    columns = [col[1] for col in columns_info]
    column_types = {col[1]: col[2].upper() for col in columns_info}
    
    # Get data from SQLite
    sqlite_cursor.execute(f"SELECT * FROM {table_name};")
    rows = sqlite_cursor.fetchall()
    
    if not rows:
        logger.info(f"No data to migrate for table {table_name}.")
        sqlite_conn.close()
        return
    
    logger.info(f"Migrating {len(rows)} rows from table {table_name}...")
    
    # Connect to PostgreSQL
    pg_conn = psycopg2.connect(**PG_PARAMS)
    pg_cursor = pg_conn.cursor()
    
    # PostgreSQL reserved keywords that need quoting
    reserved_keywords = ['user', 'group', 'order', 'table', 'select', 'where', 'from', 'limit', 'offset', 'having']
    
    # Check if table name is a reserved keyword and quote it if necessary
    pg_table_name = f'"{table_name}"' if table_name.lower() in reserved_keywords else table_name
    
    # Quote column names if they are reserved keywords
    pg_columns = [f'"{col}"' if col.lower() in reserved_keywords else col for col in columns]
    
    # Prepare column string for INSERT
    columns_str = ', '.join(pg_columns)
    placeholders = ', '.join(['%s'] * len(columns))
    
    # Convert data types as needed
    converted_rows = []
    for row in rows:
        converted_row = []
        for i, value in enumerate(row):
            col_name = columns[i]
            col_type = column_types.get(col_name, '').upper()
            
            # Handle type conversions
            if value is not None:
                # Convert SQLite boolean (0/1) to PostgreSQL boolean
                if 'BOOL' in col_type and isinstance(value, int):
                    value = bool(value)
                # Convert datetime strings if needed
                elif ('TIMESTAMP' in col_type or 'DATETIME' in col_type) and isinstance(value, str):
                    try:
                        value = datetime.datetime.fromisoformat(value)
                    except ValueError:
                        try:
                            value = datetime.datetime.strptime(value, '%Y-%m-%d %H:%M:%S')
                        except ValueError:
                            pass  # Keep as string if parsing fails
            
            converted_row.append(value)
        
        converted_rows.append(tuple(converted_row))
    
    # Use batch insert for efficiency
    batch_size = 1000
    for i in range(0, len(converted_rows), batch_size):
        batch = converted_rows[i:i+batch_size]
        try:
            pg_cursor.executemany(
                f"INSERT INTO {pg_table_name} ({columns_str}) VALUES ({placeholders})",
                batch
            )
            pg_conn.commit()
            logger.info(f"Inserted batch {i//batch_size + 1} of {(len(converted_rows)-1)//batch_size + 1} for table {table_name}")
        except Exception as e:
            pg_conn.rollback()
            logger.error(f"Error inserting batch for table {table_name}: {str(e)}")
            
            # Log the first row of the batch to help debug
            if batch:
                logger.error(f"First row of problematic batch: {batch[0]}")
                
                # Try inserting rows one by one to identify problematic records
                for j, row in enumerate(batch):
                    try:
                        pg_cursor.execute(
                            f"INSERT INTO {pg_table_name} ({columns_str}) VALUES ({placeholders})",
                            row
                        )
                        pg_conn.commit()
                    except Exception as e2:
                        pg_conn.rollback()
                        logger.error(f"Error at row {i+j}: {e2}")
                        logger.error(f"Problematic row: {row}")
                        
                        # Try to provide more detailed error information
                        for k, (col, val) in enumerate(zip(columns, row)):
                            logger.info(f"Column {col}: {val} (type: {type(val).__name__})")
            
            raise
    
    # Clean up
    sqlite_conn.close()
    pg_cursor.close()
    pg_conn.close()
    
    logger.info(f"Data migration completed for table {table_name}.")

def convert_to_timescaledb():
    """Convert measurement table to TimescaleDB hypertable"""
    conn = psycopg2.connect(**PG_PARAMS)
    conn.autocommit = False  # Start with autocommit off for transactional operations
    cursor = conn.cursor()
    
    try:
        logger.info("Preparing measurement table for TimescaleDB conversion...")
        
        # First, drop the primary key constraint
        cursor.execute("""
            ALTER TABLE measurement DROP CONSTRAINT IF EXISTS measurement_pkey CASCADE;
        """)
        
        # Add a new primary key that includes the timestamp column
        cursor.execute("""
            ALTER TABLE measurement ADD PRIMARY KEY (id, timestamp);
        """)
        
        # Commit these changes
        conn.commit()
        
        logger.info("Converting measurement table to TimescaleDB hypertable...")
        
        # Now convert to hypertable
        cursor.execute(
            "SELECT create_hypertable('measurement', 'timestamp', if_not_exists => TRUE, migrate_data => TRUE);"
        )
        
        # Create indexes for better performance
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_measurement_tank_time ON measurement (tank_id, timestamp DESC);"
        )
        
        # Commit these changes
        conn.commit()
        
        # Set autocommit to True for materialized view creation
        conn.autocommit = True
        
        logger.info("Creating continuous aggregation views...")
        
        # Set up continuous aggregation - these need to be outside a transaction
        cursor.execute("""
            CREATE MATERIALIZED VIEW IF NOT EXISTS measurements_hourly
            WITH (timescaledb.continuous) AS
            SELECT 
                tank_id,
                time_bucket('1 hour', timestamp) AS bucket,
                AVG(pressure) AS pressure,
                AVG(temperature) AS temperature,
                AVG(level) AS level,
                AVG(volume) AS volume,
                AVG(flow_rate) AS flow_rate,
                AVG(fill_percent) AS fill_percent,
                MAX(status) AS status
            FROM measurement
            GROUP BY tank_id, bucket;
        """)
        
        cursor.execute("""
            CREATE MATERIALIZED VIEW IF NOT EXISTS measurements_daily
            WITH (timescaledb.continuous) AS
            SELECT 
                tank_id,
                time_bucket('1 day', timestamp) AS bucket,
                AVG(pressure) AS pressure,
                AVG(temperature) AS temperature,
                AVG(level) AS level,
                AVG(volume) AS volume,
                AVG(flow_rate) AS flow_rate,
                AVG(fill_percent) AS fill_percent,
                MAX(status) AS status
            FROM measurement
            GROUP BY tank_id, bucket;
        """)
        
        # Turn autocommit off again for the retention policy
        conn.autocommit = False
        
        # Set retention policy
        cursor.execute(
            "SELECT add_retention_policy('measurement', INTERVAL '90 days');"
        )
        
        conn.commit()
        logger.info("Successfully converted measurement table to TimescaleDB hypertable.")
        
    except Exception as e:
        if not conn.autocommit:
            conn.rollback()
        logger.error(f"Error converting to TimescaleDB: {str(e)}")
        raise
    finally:
        cursor.close()
        conn.close()

def migrate_sqlite_to_timescaledb():
    """Main migration function"""
    start_time = time.time()
    
    try:
        logger.info("Starting migration from SQLite to TimescaleDB...")
        
        # Step 1: Create tables in PostgreSQL
        create_postgres_tables()
        
        # Step 2: Migrate data for each table
        tables = get_sqlite_tables()
        for table_name in tables:
            if table_name == 'sqlite_sequence':
                continue  # Skip SQLite internal tables
            migrate_table_data(table_name)
        
        # Step 3: Convert measurement table to TimescaleDB hypertable
        convert_to_timescaledb()
        
        elapsed_time = time.time() - start_time
        logger.info(f"Migration completed successfully in {elapsed_time:.2f} seconds!")
        
    except Exception as e:
        elapsed_time = time.time() - start_time
        logger.error(f"Migration failed after {elapsed_time:.2f} seconds: {str(e)}")
        raise

if __name__ == "__main__":
    migrate_sqlite_to_timescaledb()
