/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: 'var(--color-brand)',
        'brand-dark': 'var(--color-brand-dark)',
        canvas: 'var(--color-canvas)',
        surface: 'var(--color-surface)',
        'surface-raised': 'var(--color-surface-raised)',
        inset: 'var(--color-inset)',
        primary: 'var(--color-text-primary)',
        secondary: 'var(--color-text-secondary)',
        muted: 'var(--color-text-muted)',
        line: 'var(--color-line)',
        'line-strong': 'var(--color-line-strong)',
        ok: 'var(--color-ok-bg)',
        'ok-fg': 'var(--color-ok-text)',
        warn: 'var(--color-warn-bg)',
        'warn-fg': 'var(--color-warn-text)',
        danger: 'var(--color-danger-bg)',
        'danger-fg': 'var(--color-danger-text)',
        info: 'var(--color-info-bg)',
        'info-fg': 'var(--color-info-text)',
        '--color-canvas': 'var(--color-canvas)',
        '--color-surface': 'var(--color-surface)',
        '--color-surface-raised': 'var(--color-surface-raised)',
        '--color-inset': 'var(--color-inset)',
        '--color-text-primary': 'var(--color-text-primary)',
        '--color-text-secondary': 'var(--color-text-secondary)',
        '--color-text-muted': 'var(--color-text-muted)',
        '--color-line': 'var(--color-line)',
        '--color-line-strong': 'var(--color-line-strong)',
        '--color-brand': 'var(--color-brand)',
        '--color-brand-dark': 'var(--color-brand-dark)',
        '--color-ok-bg': 'var(--color-ok-bg)',
        '--color-ok-text': 'var(--color-ok-text)',
        '--color-warn-bg': 'var(--color-warn-bg)',
        '--color-warn-text': 'var(--color-warn-text)',
        '--color-danger-bg': 'var(--color-danger-bg)',
        '--color-danger-text': 'var(--color-danger-text)',
        '--color-info-bg': 'var(--color-info-bg)',
        '--color-info-text': 'var(--color-info-text)',
      },
    },
  },
  plugins: [],
};
